global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'bookstore-api'
    static_configs:
      - targets: ['api:8080']
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      format: ['prometheus']